### ISSUE TITLE
package published incorrectly and fails type checking in consuming projects 

### ISSUE THREAD

**Issue by NullVoxPopuli** [CrowdStrike/ember-velcro#190]
From npm, the currently published assets:

![Screenshot_20240414-085247](https://github.com/CrowdStrike/ember-velcro/assets/199018/7d083f12-5abf-45ff-bedc-9be3ea43af48)
![image-2~2](https://github.com/CrowdStrike/ember-velcro/assets/199018/30c03125-b832-484c-ab10-9a23cd821bb7)

Idk what happened to that ember-modifier import, but that's not a valid syntax, afaik

**Comment by miguelcobain** [comment]
From what I could understand, it seems that the problem is when TypeScript is generating the declaration file, more specifically the return type of `modifier` for the `velcroHook` property.
That's when it generates the `import("ember-modifier/.")` line:
```ts
velcroHook: import("ember-modifier/.").FunctionBasedModifier<{
    Element: HTMLElement | SVGElement;
    Args: {
        Named: import("ember-modifier/-private/signature").EmptyObject;
        Positional: [];
    };
}>;
```
    

However, if add the following lines on the component's index.ts file
```ts

import type { FunctionBasedModifier } from 'ember-modifier';
import type { EmptyObject } from 'ember-modifier/-private/signature.js';
```

Then this appears to serve as a "hint" to typescript, and the generated declaration is:

```ts
import { FunctionBasedModifier } from 'ember-modifier';
import { EmptyObject } from 'ember-modifier/-private/signature.js';

// ...

velcroHook: FunctionBasedModifier<{
    Element: HTMLElement | SVGElement;
    Args: {
        Named: EmptyObject;
        Positional: [];
    };
}>;
```

I lack the knowledge to instruct typescript to generate the correct declaration, but hopefully this helps.

**Comment by miguelcobain** [comment]
Another find: in the consuming app, if I go into `node_modules/ember-velcro/dist/components/velcro/index.d.ts` and make this change
```diff
-velcroHook: import("ember-modifier/.").FunctionBasedModifier<{
+velcroHook: import("ember-modifier").FunctionBasedModifier<{
    Args: {
        Positional: unknown[];
        Named: import("ember-modifier/-private/signature").EmptyObject;
    };
    Element: HookSignature;
}>;
```

then the typecheck on the app works!
So, seems like the only problem is that `/.`. 🤔
